library(sqldf)
Dat <- read.csv.sql("./data/household_power_consumption.txt",sql="select * from file where Date in ('1/2/2007','2/2/2007')",header=TRUE,sep=";")
Dat$Date<-as.Date(Dat$Date,"%d/%m/%Y")
Dat$DateTime<-as.POSIXct(paste(Dat$Date,Dat$Time))
library(datasets)
plot(Dat$Sub_metering_1~Dat$DateTime,type="l",xlab="",ylab="Energy Sub Metering")
lines(Dat$Sub_metering_2~Dat$DateTime,col="red")
lines(Dat$Sub_metering_3~Dat$DateTime,col="blue")
legend("topright",lty=1,lwd=3,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))