library(sqldf)
Dat <- read.csv.sql("./data/household_power_consumption.txt",sql="select * from file where Date in ('1/2/2007','2/2/2007')",header=TRUE,sep=";")
Dat$Date<-as.Date(Dat$Date,"%d/%m/%Y")
Dat$DateTime<-as.POSIXct(paste(Dat$Date,Dat$Time))
library(datasets)
png(file="plot4.png",height = 480,width = 480)
par(mfrow=c(2,2))
with(Dat,{
    plot(Global_active_power~DateTime,type="l",xlab="",ylab="Global Active Power")
    plot(Voltage~DateTime,type="l",xlab="datetime",ylab="Voltage")
    plot(Sub_metering_1~DateTime,type="l",xlab="",ylab="Energy Sub Metering")
    lines(Sub_metering_2~DateTime,col="red")
    lines(Sub_metering_3~DateTime,col="blue")
    legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
    plot(Global_reactive_power~DateTime,type="l",xlab="datetime",ylab="Global_reactive_power")
})